# BYKT Installation Script for Windows
# Usage: irm https://raw.githubusercontent.com/dx111ge/bykt/main/install.ps1 | iex

$ErrorActionPreference = "Stop"

$RepoRaw = "https://raw.githubusercontent.com/dx111ge/bykt/main"
$InstallDir = if ($env:BYKT_INSTALL_DIR) { $env:BYKT_INSTALL_DIR } else { ".\bykt" }

Write-Host "Installing BYKT to $InstallDir..." -ForegroundColor Cyan

# Create directory structure
New-Item -ItemType Directory -Force -Path "$InstallDir\traefik-config" | Out-Null
Set-Location $InstallDir

# Download docker-compose
Write-Host "Downloading docker-compose.prod.yml..."
Invoke-WebRequest -Uri "$RepoRaw/docker-compose.prod.yml" -OutFile "docker-compose.prod.yml"

# Download traefik config
Write-Host "Downloading traefik configuration..."
Invoke-WebRequest -Uri "$RepoRaw/traefik-config/traefik.yml" -OutFile "traefik-config\traefik.yml"
Invoke-WebRequest -Uri "$RepoRaw/traefik-config/dynamic.yml" -OutFile "traefik-config\dynamic.yml"

# Generate secure random secrets
Write-Host "Generating .env with secure secrets..."
function Get-RandomHex($length) {
    $bytes = New-Object byte[] $length
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
    return [System.BitConverter]::ToString($bytes) -replace '-', ''
}

$SecretKey = Get-RandomHex 32
$JwtSecret = Get-RandomHex 32
$PostgresPassword = Get-RandomHex 16

# Generate .env file
@"
# BYKT Configuration
# Generated by install script on $(Get-Date)

# Database
POSTGRES_DB=bykt
POSTGRES_USER=bykt
POSTGRES_PASSWORD=$PostgresPassword

# Security - auto-generated secrets
SECRET_KEY=$SecretKey
JWT_SECRET_KEY=$JwtSecret

# Ollama LLM (adjust if Ollama runs on different host)
OLLAMA_BASE_URL=http://host.docker.internal:11434
OLLAMA_MODEL=qwen2.5:7b

# App URL (change if using custom domain)
NEXT_PUBLIC_APP_URL=http://127.0.0.1
"@ | Out-File -FilePath ".env" -Encoding UTF8

Write-Host ""
Write-Host "========================================" -ForegroundColor Green
Write-Host "  BYKT installed successfully!" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Green
Write-Host ""
Write-Host "Next steps:"
Write-Host "  1. Ensure Ollama is running: ollama serve"
Write-Host "  2. Pull the models:"
Write-Host "     ollama pull qwen2.5:7b"
Write-Host "     ollama pull nomic-embed-text-v2-moe:latest"
Write-Host "  3. Start BYKT: docker compose -f docker-compose.prod.yml up -d"
Write-Host "  4. Open http://127.0.0.1"
Write-Host ""
Write-Host "Login credentials:"
Write-Host "  Username: admin"
Write-Host "  Password: admin"
Write-Host ""
Write-Host "For public access via Cloudflare tunnel:"
Write-Host "  docker compose -f docker-compose.prod.yml --profile tunnel up -d"
Write-Host "  docker logs bykt-cloudflared  # Get your public URL"
Write-Host ""
