#!/bin/bash
# BYKT Installation Script for Linux/Mac
# Usage: curl -sSL https://raw.githubusercontent.com/dx111ge/bykt/main/install.sh | bash

set -e

REPO_RAW="https://raw.githubusercontent.com/dx111ge/bykt/main"
INSTALL_DIR="${BYKT_INSTALL_DIR:-./bykt}"

echo "Installing BYKT to $INSTALL_DIR..."

# Create directory structure
mkdir -p "$INSTALL_DIR/traefik-config"
cd "$INSTALL_DIR"

# Download docker-compose
echo "Downloading docker-compose.prod.yml..."
curl -sSL "$REPO_RAW/docker-compose.prod.yml" -o docker-compose.prod.yml

# Download traefik config
echo "Downloading traefik configuration..."
curl -sSL "$REPO_RAW/traefik-config/traefik.yml" -o traefik-config/traefik.yml
curl -sSL "$REPO_RAW/traefik-config/dynamic.yml" -o traefik-config/dynamic.yml

# Generate .env with secure random secrets
echo "Generating .env with secure secrets..."
SECRET_KEY=$(openssl rand -hex 32 2>/dev/null || head -c 64 /dev/urandom | base64 | tr -dc 'a-zA-Z0-9' | head -c 64)
JWT_SECRET=$(openssl rand -hex 32 2>/dev/null || head -c 64 /dev/urandom | base64 | tr -dc 'a-zA-Z0-9' | head -c 64)
POSTGRES_PASSWORD=$(openssl rand -hex 16 2>/dev/null || head -c 32 /dev/urandom | base64 | tr -dc 'a-zA-Z0-9' | head -c 32)

cat > .env << EOF
# BYKT Configuration
# Generated by install script on $(date)

# Database
POSTGRES_DB=bykt
POSTGRES_USER=bykt
POSTGRES_PASSWORD=$POSTGRES_PASSWORD

# Security - auto-generated secrets
SECRET_KEY=$SECRET_KEY
JWT_SECRET_KEY=$JWT_SECRET

# Ollama LLM (adjust if Ollama runs on different host)
OLLAMA_BASE_URL=http://host.docker.internal:11434
OLLAMA_MODEL=qwen2.5:7b

# App URL (change if using custom domain)
NEXT_PUBLIC_APP_URL=http://127.0.0.1
EOF

echo ""
echo "========================================"
echo "  BYKT installed successfully!"
echo "========================================"
echo ""
echo "Next steps:"
echo "  1. Ensure Ollama is running: ollama serve"
echo "  2. Pull the model: ollama pull qwen2.5:7b"
echo "  3. Start BYKT: cd $INSTALL_DIR && docker compose -f docker-compose.prod.yml up -d"
echo "  4. Open http://127.0.0.1"
echo ""
echo "Login credentials:"
echo "  Username: admin"
echo "  Password: admin"
echo ""
echo "For public access via Cloudflare tunnel:"
echo "  docker compose -f docker-compose.prod.yml --profile tunnel up -d"
echo "  docker logs bykt-cloudflared  # Get your public URL"
echo ""
